### ISSUE TITLE
[Feature Request] User Authentication needed

### ISSUE THREAD

**Issue by dmotts** [dmotts/yt-to-cloud-uploader#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

User's would be able to register and sign in through email/password.

### Use Case

User will be able to save their settings.

### Benefits

- Improved functionality 
- Improved user experience

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by Brijeshthummar02** [comment]
can you show me the path where to add file.

**Comment by dmotts** [comment]
Hey @Brijeshthummar02, it should be in the [main.py](https://github.com/dmotts/yt-to-cloud-uploader/blob/main/main.py). However, the app is not setting up correctly for some users so I will raise that as an issue.

**Comment by Brijeshthummar02** [comment]
Should i start working on it or wait till you open the issue.

**Comment by dmotts** [comment]
I have opened the issue #21. So you can take a pause on this issue for now as it depends on the other one being resolved first. 

Thanks again for being invested in this project! 😀

**Comment by dmotts** [comment]
Hey @Brijeshthummar02 since this is a duplicate issue #28. I'll close it. Let me know if you have any questions.
