### ISSUE TITLE
[Documentation Update] Logo needed 

### ISSUE THREAD

**Issue by dmotts** [dmotts/yt-to-cloud-uploader#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This app requires an appealing logo to attract more users and team members.

### Suggested Change

Create a logo.

### Rationale

This will build YouTube  to Cloud Uploader as a brand and build trustworthiness with it's users. It will also improve the marketing of the app.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by shawaiz-khan** [comment]
Can I do this?

**Comment by dmotts** [comment]
Of course @shawaiz-khan! It is awesome to have you on the team! Thanks for contributing @shawaiz-khan!

**Comment by shawaiz-khan** [comment]
Thank You

**Comment by shawaiz-khan** [comment]
Just final touches are left!

**Comment by dmotts** [comment]
@shawaiz-khan Awesome! 😁

 Let's go! 💪💯

**Comment by shawaiz-khan** [comment]
![Logo-01](https://github.com/user-attachments/assets/1cb5ea7a-5531-4945-9f0f-a9ae6db6392d)
How to open a pr? I am asking for hacktoberfest

**Comment by dmotts** [comment]
@shawaiz-khan Awesome work! Here's the PR [link](https://github.com/dmotts/yt-to-cloud-uploader/compare). In the future, you could use the 'New Pull Request' button located in 'Pull Requests' at the top right of the section.

Thank you for being a part of this.

**Comment by shawaiz-khan** [comment]
Let me fork it and I will add the files to the logo folder in the root. is that okay?

**Comment by dmotts** [comment]
@shawaiz-khan you may review our [community guidelines](https://github.com/dmotts/yt-to-cloud-uploader/blob/main/CONTRIBUTING.md) for a more detailed guide on how to contribute to the project.

I'm available if you encounter any challenges during the process.

**Comment by shawaiz-khan** [comment]
Done!

**Comment by shawaiz-khan** [comment]
Thank You
