### ISSUE TITLE
[Feature Request] Update project structure to better allow easy expansion

### ISSUE THREAD

**Issue by HomerusJa** [dmotts/yt-to-cloud-uploader#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Currently, the whole project is located in one file. Looking at the current feature requests to add Onedrive and Dropbox integration (#12, #13), this file would just become really large and rather hard to understand.

To fix this, I would opt for a layout, where the different integrations are moved into a core folder. As you can see below, I would structure the different components by the service they relate to.

```txt
.
├── main.py
└── core/
    ├── base.py
    ├── youtube.py
    ├── gcloud.py
    ├── onedrive.py
    └── dropbox.py
```

You could debate about the naming of some of these files. `base.py` should include base classes (if needed). I would suggest leaving the main.py at the project root to let the command `streamlit run main.py` still work.

### Use Case

As described above, this would allow for easier expansion of this project in the future.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by dmotts** [comment]
Hey @HomerusJa, this may be random BUT I'm curious. 

What's the coolest thing you ever built with Arduino? (I noticed you have it on your GitHub profile, it caught my attention...)

**Comment by HomerusJa** [comment]
For example, I am currently building a camera system which can automatically send the images, receive new configuration and so on via an infrastructure called S3I (basically a message queue with standardized message formats). Here, the one camera is just one of many devices interacting with each other.

I also built a controller for a hovercraft with some friends with an ESP32 (Those are just better than every Arduino in every way) incorporating a web server with a config page and an online remote control.

**Comment by HomerusJa** [comment]
Now I am curious. What do you mean by an AI consultant? What are you doing as your everyday job?

**Comment by dmotts** [comment]
Hey @HomerusJa, I like the idea of using the Arduino to expand the features of your security camera system. That's cool. I had an Arduino but I didn't get to use it as much, just did the tutorials unfortunately.

Now, as for my everyday job. I'm really an IT consultant however to stay ahead of the curve, I changed the title. Also, most of the questions ask nowadays are about AI. So, I mostly come up with a IT / AI solution for my clientele and upsell them on other services that I offer. So it could be something simple like my prospect's offiice doesn't have an local network setup and I'll let them know there's way they could send files securely without the risk of it being leaked on the internet then I'll setup the network and from there, they usually ask for more.

However, it could get time consuming after awhile and my passion is in AI right now. So, I'm looking to more away from that part of the job and focus entirely on build AI applications.

**Comment by HomerusJa** [comment]
Sounds nice! The arduinos framework combined with the ESP32 is such a nice platform if you want to have devices on the edge and stuff. If you build your own projects with electronics, it is unquestionably one of the best platforms out there.
