### ISSUE TITLE
[Documentation Update]: Update README.md

### ISSUE THREAD

**Issue by HomerusJa** [dmotts/yt-to-cloud-uploader#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

After #38, the README is outdated, especially the categories of technologies used and contributing (already worked on in #40)

### Suggested Change

Fix this.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by dmotts** [comment]
This issue has been brought up before.
