### ISSUE TITLE
[Documentation Update]: Finish documenting the architecture

### ISSUE THREAD

**Issue by HomerusJa** [dmotts/yt-to-cloud-uploader#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

In the docs folder, there are currently two files describing the different sites and the different endpoints. This doesnt document the technologies we want to use.

### Suggested Change

Create a `technologies.md` in which the different technologies and associated design decisions are explained.

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by KrinsKumar** [comment]
Hey Can I work on this, if yes please assign this to me!!.

**Comment by dmotts** [comment]
Sure @KrinsKumar! If you have any questions or concerns, please feel free to ask someone.

**Comment by i-Tohka** [comment]
> Sure @KrinsKumar! If you have any questions or concerns, please feel free to ask someone.

In your endpoints document, you state that you want to use a username/password system; however, you are are also wanting to use Oauth2 and the Google Drive API for sign-in which does not require user/pass. Is it alright if the technologies.md is updated to reflect the latter? If so, then it would probably be a good idea to update the endpoints.md as well.

**Comment by dmotts** [comment]
@i-Tohka, before I say. This is open to contributors only for the moment.

Would you like to join in our [Discord](https://discord.com) server? If so, feel free to message me and I'll send you an invite link.

**Comment by i-Tohka** [comment]
I am not really looking to be a primary contributor or anything. I came across your project after searching for help wanted with documentation issues. It seemed like a nice clean slate for me to learn and grow as a technical writer. I will mostly be ghosting this project with my own fork and maybe would be willing to be more active, join your server, in the future. I appreciate the offer though.

**Comment by dmotts** [comment]
That awesome @i-Tohka! I have a question, if you don't mind me asking. Where did you find out about us?

**Comment by i-Tohka** [comment]
As I mentioned, through the github advanced search function.

**Comment by dmotts** [comment]
Great! I know it's not an "official" but thank you so much for your contribution! 😀
