### ISSUE TITLE
[Feature Request] API required to download videos from YouTube

### ISSUE THREAD

**Issue by dmotts** [dmotts/yt-to-cloud-uploader#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

This app requires an API to download videos from YouTube.

### Use Case

User will input link on the landing page and the video will be download to the app to be store on a cloud storage of the user's choice.

### Benefits

- Improved functionality 

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by RedLordezh7Venom** [comment]
please assign me on this
i can try working on this
