### ISSUE TITLE
[Documentation Update]: CONTRIBUTION.md Needed

### ISSUE THREAD

**Issue by dmotts** [dmotts/yt-to-cloud-uploader#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

This repository should have a Contribution Guidelines page.

### Suggested Change

Add CONTRIBUTION.md file to the project.

### Rationale

Thus will show developers how they can contribute to the project with minimal confusion.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by Brijeshthummar02** [comment]
hello there, i can add this.
@dmotts

**Comment by dmotts** [comment]
Okay, I'll assign the task to you.

**Comment by dmotts** [comment]
@Brijeshthummar02 Can you make it similar to this one [https://github.com/dmotts/ai-insights/blob/main/CONTRIBUTION.md](CONTRIBUTION.md)?

**Comment by dmotts** [comment]
@Brijeshthummar02  Do you need any assistance? We can re-assign if you're unable to finish. Feel free to message anyone on the team for help or if you have any questions. 👍
