### ISSUE TITLE
[Documentation Update]: Add missing requirements.txt file

### ISSUE THREAD

**Issue by IngaleChinmay04** [dmotts/yt-to-cloud-uploader#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The repository is missing a requirements.txt file that lists all the dependencies needed for this project. This file is crucial for users who want to set up the environment and run the project without errors.

### Suggested Change

Add a requirements.txt file to the repository. This file should contain a list of all Python packages and their versions used in the project. 

### Rationale

Including a requirements.txt file makes it easier for developers and users to set up the environment and run the project correctly.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by dmotts** [comment]
This issue is dependant on #46 #49 #48

**Comment by Akshay-66** [comment]
@dmotts Done with the requirements,txt file.
