### ISSUE TITLE
[Documentation Update]: Add hyperlinks to README.md

### ISSUE THREAD

**Issue by dmotts** [dmotts/yt-to-cloud-uploader#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

There aren't any links to the technologies used in the README MD file.

![Screenshot_20241011-165759](https://github.com/user-attachments/assets/98496209-998f-4ae7-b299-f3a56e326712)

### Suggested Change

Add links to the official websites of the technologies used.

![IMG_20241011_170951](https://github.com/user-attachments/assets/f38193f1-5dac-4d75-af7f-0cb171c942db)

### Rationale

This will help visitors easily navigate to the official documentation of the technologies used in the project and thus, they will be understand how the project works quicker.

### Urgency

Low

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

**Comment by swarupn17** [comment]
Hey @dmotts I can do this task please can you assign it to me.
Thanks!

**Comment by dmotts** [comment]
Sure thing, thanks for your help!
